name: Update EC2 Security Group

on:
  schedule:
    - cron: "0 0 * * *" # Daily update
  workflow_dispatch:

jobs:
  update-sg:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Get GitHub IPs and update SG
        run: |
          # Install jq
          sudo apt-get install -y jq

          # Get current GitHub IPs
          IPS=$(curl -s https://api.github.com/meta | jq -r '.actions[]')

          # Revoke old rules
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr 0.0.0.0/0 || true

          # Add new rules
          for ip in $IPS; do
            aws ec2 authorize-security-group-ingress \
              --group-id ${{ secrets.SECURITY_GROUP_ID }} \
              --protocol tcp \
              --port 22 \
              --cidr $ip
          done
